### ISSUE TITLE
Setup smart contract repo

### ISSUE THREAD

**Issue by webmaster128** [iov-one/ethereum-smart-contracts#1]
- [x] Apache-2 licence (copy from iov core)
- [x]  No external contributors
- [x]  Rewrite contract from scratch
- [x]  TDD?
- [x]  Focus on Ether only first
- [x]  Renaming
- [x]  Events in past tense
- [x]  Move state into struct
- [x]  Combine `check` and `checkSecret`
- [x]  Remove Pausable
- [x]  Linting
- [x]  Look into etheno [not necessary for now]
- [x]  Analysis scripts (slither, manticore, truffle-security)
- [x]  Truffle/ganache
- [ ]  CI setup (especially for linting)

**Comment by webmaster128** [comment]
Looking at the import statements in https://github.com/nomiclabs/truffle-flattener/tree/master/tests/contracts, it seems like truffle (or maybe only truffle-flattener) is able to import the contracts from node_modules automatically. That way we can use OpenZeppelin imports via npm instead of copying the files.

**Comment by webmaster128** [comment]
Removed

```
Further issues:
- [ ]  ERC20 implementation
- [ ]  Use OpenZeppelin
- [ ]  Consider git submodules for OpenZeppelin if enough files
- [ ]  Make Mintable for testing purposes
```

from the original list in this ticket, which is now covered by #7 and #8

**Comment by ethanfrey** [comment]
Done. Made CI setup it's own issue #16
