### ISSUE TITLE
Helper scripts to compile Solidity to bytecode

### ISSUE THREAD

**Issue by ethanfrey** [iov-one/ethereum-smart-contracts#2]
When adding custom contracts to the ethereum chain (or our test chain), we will need to compile some human-readable solidity into evm bytecode, so it can be uploaded.

`truffle` toolkit will compile and upload together. We should choose and document some tools we can use to compile into one file that we can upload separately.

**Acceptance Criteria**

- [ ] Add description of the tooling to a README in iov-ethereum package (we can also extend section on ganache)
- [ ] Copy a [reference erc20 contract](https://github.com/OpenZeppelin/openzeppelin-solidity/blob/master/contracts/token/ERC20/ERC20.sol) to a folder under `scripts/ethereum` for tests
- [ ] Add a script to `scripts/ethereum` to compile this contract and save the output in another directory
- [ ] Make sure to expose the ABI (method definitions) as well as the raw bytecode

**Comment by webmaster128** [comment]
Example of compile .sol, deploy to ganache and test:
https://github.com/LucasIsasmendi/ganache-jest-example/blob/master/test/erc20.test.js

**Comment by webmaster128** [comment]
As discussed, the compilation from.sol into bytecode will happen here in the smart contract development repo. Thus acceptence criteria are outdated now. With #5 merged we have all we need

- flattening
- compilation into `./build/contracts/*.json` that includes ABI and bytecode
