### ISSUE TITLE
Deploy smart contract given ABI and bytecode

### ISSUE THREAD

**Issue by ethanfrey** [iov-one/ethereum-smart-contracts#6]
Builds on https://github.com/iov-one/ethereum-smart-contracts/issues/2

With web3, you can connect to a contract via:
`let contract = web3.eth.contract(PASTE ABI HERE!);`

And set the bytecode once via:
`contract.new({from.., gas..., data: "PASTE_HEX_BYTECODE_HERE"})`

We should upload via iov-core/iov-etherum code.
At this stage we can use web3/truffle/etc tooling to validate the data is properly writen to the blockchain, by querying the address.

**Acceptance Criteria**
- [ ] Given ABI and Bytecode, and an account with some funds, upload contract to ganache
- [ ] Create a iov-ethereum specific UnsignedTransaction to represent this (`CreateContractTransaction` ?)
- [ ] Validate the contract can be viewed via web3 and the bytecode is properly stored.

**Comment by webmaster128** [comment]
Example of compile .sol, deploy to ganache and test:
https://github.com/LucasIsasmendi/ganache-jest-example/blob/master/test/erc20.test.js

**Comment by webmaster128** [comment]
web3x does an incredible job generating typescript classes for contracts including bytecode for deployment. At this point we might reconsider splitting deployment and usage of smart contracts, since we get deployment code for free if we use web3x in @iov/ethereum.

Let's create an ERC20 token to test the whole flow locally.

**Comment by ethanfrey** [comment]
Ahh... here is the compile step. Seems easy enough...

https://github.com/LucasIsasmendi/ganache-jest-example/blob/master/utils/compile.js

**Comment by webmaster128** [comment]
Covered by the subproject in scripts/ethereum/deployment of https://github.com/iov-one/iov-core/pull/846

**Comment by ethanfrey** [comment]
@webmaster128 sounds good, please close that when that pr is merged. This is what I wanted
